version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:latest
    restart: on-failure
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306

  php:
    image: pubreg.shopping.check24-test.de/repository/docker-public/alpine-php:8.0
    restart: on-failure
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?serverVersion=8.0
    links:
      - mysql
    volumes:
      - ".:/var/www"

  nginx:
    image: pubreg.shopping.check24-test.de/repository/docker-public/nginx-default:latest
    restart: on-failure
    depends_on:
      - php
    volumes:
      - ".:/var/www"
    ports:
      - 80:80

volumes:
  dbdata:
